# Generated by Django 2.2.10 on 2020-05-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'poll answer',
                'verbose_name_plural': 'poll answers',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(verbose_name='Text answer')),
                ('choice_answer', models.ManyToManyField(to='polls.Choice')),
                ('poll_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='answers.PollAnswer', verbose_name='Poll answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='polls.Question', verbose_name='Question')),
            ],
        ),
    ]
